services:
  ros2_jazzy_arm_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_jazzy_arm_dev
    
    # ... (Rest van je configuratie blijft hetzelfde) ...
    runtime: nvidia
    command: sleep infinity
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    
    volumes:
      # GUI toegang
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # USB toegang
      - /dev/bus/usb:/dev/bus/usb:rw
      
      # Config files Ublox
      - ./config/ras_sensorbox/ublox/:/root/ros2_ws/install/ras_sensorbox/share/ras_sensorbox/config/:rw

      # Config files ntrip_client
      - ./config/ras_sensorbox/ntrip_client/:/root/ros2_ws/install/ras_sensorbox/share/ras_sensorbox/config/:rw


      # Config files velodyne
      - ./config/ras_sensorbox/velodyne/:/root/ros2_ws/install/ras_sensorbox/share/ras_sensorbox/config/:rw


      # Config files pylon_ros_camera
      - ./config/ras_sensorbox/ublox/:/root/ros2_ws/install/ras_sensorbox/share/ras_sensorbox/config/:rw



